### ISSUE TITLE
It seems some files missed in "dynamic-update" branch?

### ISSUE THREAD

**Issue by ziji-wu** [SpectraSynthesizer/spectra-synt#11]
How great this tool is!
However, when I try to configure this project, some import errors occurred in the file `/tau.smlab.syntech.spectragameinput/src/tau/smlab/syntech/spectragameinput/translator/FeatureConstraintTranslator.java` under the "dynamic-update" branch. 
`import tau.smlab.syntech.spectra.FeatureAndExpr;
import tau.smlab.syntech.spectra.FeatureIffExpr;
import tau.smlab.syntech.spectra.FeatureImpExpr;
import tau.smlab.syntech.spectra.FeatureOrExpr;`

I searched all the GitHub and cannot found such four files, is it be forgot when upload the code of "dynamic-update" branch?
Thanks a lot if one can solve this problem.

**Comment by iliashevrin** [comment]
Hi @ziji-wu ,
The files are indeed unnecessary in this branch. I removed them in a recent commit. Please pull and check again.

**Comment by ziji-wu** [comment]
Thanks a lot! This problem didn't occurred after I pull and merge the latest codes.
